### ISSUE TITLE
Agregar Oswald (se va a usar en las plantillas de huayra-curriculum)

### ISSUE THREAD

**Issue by iglosiggio** [HuayraLinux/huayra-fonts#1]
En la plantilla de huayra-curriculum diseñada por @DiegoAccorinti está esta tipografía en uso, la [licencia](https://github.com/googlefonts/OswaldFont/blob/master/OFL.txt) parece permitir su inclusión sin dramas.

Fuente: https://fonts.google.com/specimen/Oswald

**Comment by DiegoAccorinti** [comment]
Agregada.
